### PR TITLE
Fix/fix bulk byte size

### LINKED ISSUE #871: Not all collection's items are added using "insert.many"
Hello,
there is an issue using insert.many. 
Mongo version:  4.0.6
Reactivemongo driver: 0.18.6

Code:
```
import reactivemongo.api.{MongoConnection, MongoDriver}
import reactivemongo.play.json.collection.JSONCollection
import play.api.libs.json.Json
import scala.concurrent.{ExecutionContext, Future}
import scala.util.Random

object GetStarted extends App {

  val stringSize = 1024

  // we expect 20000 documents will be inserted to test_col collection but
  // by running this script db.getCollection('test_col').count() 
  // we can see that just 3930 were added
  val collectionSize = 20000

  import ExecutionContext.Implicits.global

  val mongoUri = "mongodb://localhost:27017/mydb?authMode=scram-sha1"
  val driver = MongoDriver()
  val parsedUri = MongoConnection.parseURI(mongoUri)
  val connection = parsedUri.map(driver.connection)
  val futureConnection = Future.fromTry(connection)

  def db = futureConnection.flatMap(_.database("test_mongo40"))

  def testCollection =
    db.map(_.collection[JSONCollection]("test_col"))

  case class TestType(someData: String)

  implicit val testTypeFormat = Json.format[TestType]

  def writeTestData(testData: Seq[TestType]) =
    testCollection.flatMap(_.insert.many(testData))

  def makeItem = TestType(Random.alphanumeric.take(stringSize).mkString)

  val items = (1 to collectionSize).map(_ => makeItem)

  writeTestData(items)

}
```

build.sbt: 
```
name := "test_mongo40"

version := "0.1"

scalaVersion := "2.11.8"
val playVersion = "2.5.2"

libraryDependencies ++= Seq(
  "com.typesafe.play" %% "play" % playVersion,
  "org.reactivemongo" %% "play2-reactivemongo" % "0.18.6-play25",
  "org.apache.logging.log4j" % "log4j-core" % "2.12.1"
)
```

Issue:
3930 documents were created instead of 20000. 

Mongo logs:
```
E -        [conn608] Assertion: BSONObjectTooLarge: BSONObj size: 16878542 (0x1018BCE) is invalid. Size must be between 0 and 16793600(16MB) First element: insert: "test_col" src/mongo/bson/bsonobj.cpp 102
```

### PR DESCRIPTION
**Pull request by AurelienRichez**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/CONTRIBUTING.md#reactivemongo-developer--contributor-guidelines)?
* [x] Have you added tests for any changed functionality?

## Fixes

Probably fixes #871 

## Purpose

Correctly compute a bulk size in BulkOps. 

Currently we do not account for the total array size of a bulk. This means that a small errors adds up in our expected byte size for each document. This ultimately makes Reactive mongo send a bulk insert command which is too big.

## Background Context
When running a bulk operation, reactive mongo cuts the Seq of documents to insert (for instance) in bulks to avoid sending a command which is bigger than the maximum byte size allowed by MongoDB. But the way we compute the bulk size seems wrong. 

**Example:** 
Say we want to insert 3 empty documents: `[{},{},{}]` . Currently we compute the size by adding the size of an empty doc 3 times, but the real bulk size is the size of the complete array`[{},{},{}]`. 

This means that we can potentially send a command over the size limit.

A BSONArray is like a BSONDocument with numeric key according to the spec [1] : `[ {}, {}, {} ] <=> { '0': {}, '1': {}, '2': {}}`. This means that when computing the size of a bulk we must also add : 
 - The type prefix : 2 bytes
 - The size of the "key", which increase as the array gets bigger (The 11th element cost actually more bytes than the first because the key '10' take two bytes)

## References

[1] http://bsonspec.org/spec.html

### CODE REVIEW

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 1]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
...
+        maxBulkSize = 2)(_.byteSize) must beLike[BulkProducer[BSONDocument]] {
+        case prod1 =>
+          prod1() must beLeft
+      }
+    }
+
+    s"take into account the fact that keys increase in size in a larger array" in {
+      val ExpectedFirstBulk = Iterator.continually(doc1).take(10).toList
+      val ExpectedSecondBulk = List(doc1)
+      val enoughSizeWithoutConsideringSizeIncrease = (doc1.byteSize + 1 + BSONElementSet.typePrefixByteSize) * 11
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]: Let keep it in `maxBsonSize` (the value is used once)

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 2]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
...
+        documents = producer2Docs,
+        maxBsonSize = doc1.byteSize,
+        maxBulkSize = 2)(_.byteSize) must beLike[BulkProducer[BSONDocument]] {
+        case prod1 =>
+          prod1() must beLeft
+      }
+    }
+
+    s"take into account the fact that keys increase in size in a larger array" in {
+      val ExpectedFirstBulk = Iterator.continually(doc1).take(10).toList
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]:
```suggestion
      val ExpectedFirstBulk = List.fill(10)(doc1)
```

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 3]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
...
+      val ExpectedSecondBulk = List(doc1)
+      val enoughSizeWithoutConsideringSizeIncrease = (doc1.byteSize + 1 + BSONElementSet.typePrefixByteSize) * 11
+
+      bulks[BSONDocument](
+        documents = Iterator.continually(doc1).take(11).toSeq,
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]:
```suggestion
        documents = Seq.fill(11)(doc1),
```

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 4]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
...
+      bulks[BSONDocument](
+        documents = producer2Docs,
+        maxBsonSize = doc1.byteSize,
+        maxBulkSize = 2)(_.byteSize) must beLike[BulkProducer[BSONDocument]] {
+        case prod1 =>
+          prod1() must beLeft
+      }
+    }
+
+    s"take into account the fact that keys increase in size in a larger array" in {
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]:
```suggestion
    "take into account the fact that keys increase in size in a larger array" in {
```

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 5]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
         }
       }
     }
+
+    s"take minimal size into account into total size" in {
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]:
```suggestion
    "take minimal size into account into total size" in {
```

File: driver/src/test/scala/BulkOpsSpec.scala [hunk 6]
```diff
@@ -79,6 +77,34 @@ class BulkOpsSpec(implicit ee: ExecutionEnv)
...
+      bulks[BSONDocument](
+        documents = producer2Docs,
+        maxBsonSize = doc1.byteSize,
+        maxBulkSize = 2)(_.byteSize) must beLike[BulkProducer[BSONDocument]] {
+        case prod1 =>
+          prod1() must beLeft
```
Comment (cchantep) [inline driver/src/test/scala/BulkOpsSpec.scala]: Expected left value?

File: bson/src/main/scala-2.13-/types.scala [hunk 7]
```diff
@@ -919,6 +919,7 @@ object BSONElementSet {
   implicit def apply(set: Traversable[BSONElement]): BSONElementSet =
     new BSONDocument(set.map(Success(_)).toStream)
 
+  private[reactivemongo] val typePrefixByteSize = 2
```
Comment (cchantep) [inline bson/src/main/scala-2.13-/types.scala]: As far as I can see/remind the [type code is written](https://github.com/ReactiveMongo/ReactiveMongo/blob/master/bson/src/main/scala/buffer/DefaultBufferHandler.scala#L81) as a single byte (or [there](https://github.com/mongodb/mongo-go-driver/blob/03f71cffc6c1b6c1de8b5c6d988d04916f4fbf7d/bson/bsonrw/value_reader.go#L684))

File: bson/src/main/scala-2.13-/types.scala [hunk 8]
```diff
@@ -907,7 +907,7 @@ sealed trait BSONElementSet extends ElementProducer { self: BSONValue =>
   override private[reactivemongo] lazy val byteSize: Int =
```
Comment (cchantep) [inline bson/src/main/scala-2.13-/types.scala]: ` bson/src/main/scala-2.13+/types.scala` ?

File: driver/src/main/scala/api/collections/BulkOps.scala [hunk 9]
```diff
@@ -65,11 +66,12 @@ private[reactivemongo] object BulkOps {
...
 
-        if (bsz > maxBsonSize) {
-          Left(s"size of document #${offset + docs} exceed the maxBsonSize: $bsz > $maxBsonSize")
+        // Total minimal size is key '1' size (1 byte) + type prefix (2 bytes)
+        if (bsz + 1 + BSONElementSet.typePrefixByteSize > maxBsonSize) {
+          Left(s"size of document #${offset + docs} exceed the maxBsonSize: $bsz + 3 > $maxBsonSize")
         } else {
           val nc = docs + 1
-          val nsz = bsonSize + bsz
+          val nsz = bsonSize + bsz + docs.toString.getBytes.length + BSONElementSet.typePrefixByteSize
```
Comment (cchantep) [inline driver/src/main/scala/api/collections/BulkOps.scala]:
```suggestion
          val keySize = docs.toString.getBytes.size // string repr. of current index used as key
          val nsz = bsonSize + bsz + keySize + BSONElementSet.typePrefixByteSize
```

Extract as `val` to comment the tricky part about key

File: bson/src/main/scala-2.13-/types.scala (hunk 7 above)
Comment (AurelienRichez) [reply bson/src/main/scala-2.13-/types.scala]: Ah yes you're right ! In fact this counts the type code and the null character from the key I guess. I'll change the name

File: driver/src/test/scala/BulkOpsSpec.scala (hunk 1 above)
Comment (AurelienRichez) [reply driver/src/test/scala/BulkOpsSpec.scala]: Will do. This was to make it clear why I choose this max size.

File: bson/src/main/scala-2.13-/types.scala (hunk 8 above)
Comment (AurelienRichez) [reply bson/src/main/scala-2.13-/types.scala]: I made the change in 2.13+
